### ISSUE TITLE
About the egl api call problem

### ISSUE THREAD

**Issue by tanglup** [patriciogonzalezvivo/comfyui_glslnodes#4]
My system is Windows. I successfully installed your node. After running it, an error occurred：
cannot import name 'egl' from 'glcontext' (D:\Airuanjian\ComfyUIbianxie\ComfyUI_windows_portable\python_embeded\Lib\site-packages\glcontext\__init__.py)
See if you can solve this problem

**Comment by patriciogonzalezvivo** [comment]
Hi! Yesterday push a commit where a different backend is assigned depending the OS https://github.com/patriciogonzalezvivo/comfyui_glslnodes/blob/main/node.py#L16-L20

Do you mind checking if it works?

**Comment by ohnoitsaninja** [comment]
I'm on windows and get

Error occurred when executing glslViewer:
Cannot find supported backend: 'wgl'

**Comment by tanglup** [comment]
> 嗨！昨天推送了一个提交，根据操作系统分配了不同的后端https://github.com/patriciogonzalezvivo/comfyui_glslnodes/blob/main/node.py#L16-L20
> 
> 您介意检查一下它是否有效吗？

A new error occurred. Even though the wgl dependency library was installed, it still prompted that the wgl backend could not be found.
moderngl and glcontext were also installed.
 My torch is pytorch version: 2.3.1+cu121  and xformers version: 0.0.27

**Comment by patriciogonzalezvivo** [comment]
Just push another https://github.com/patriciogonzalezvivo/comfyui_glslnodes/commit/21d63f747d66f5217d60fc7c26a7c00ea66ad562. Do you mind giving it a try?

Sorry for the back and forth.

**Comment by baram892** [comment]
> I'm on windows and get
> 
> Error occurred when executing glslViewer: Cannot find supported backend: 'wgl'

I have the same issue

**Comment by patriciogonzalezvivo** [comment]
Do you mind updating and trying again?

**Comment by baram892** [comment]
I tried again, but I got the same issue.
I use comfyUI portable. is this a problem?

**Comment by baram892** [comment]
Error occurred when executing glslViewer:

Cannot find supported backend: 'wgl'

File "I:\AI\AI_202406\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "I:\AI\AI_202406\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "I:\AI\AI_202406\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "I:\AI\AI_202406\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_glslnodes\node.py", line 108, in main
ctx = moderngl.create_context(
^^^^^^^^^^^^^^^^^^^^^^^^
File "I:\AI\AI_202406\ComfyUI_windows_portable\python_embeded\Lib\site-packages\moderngl\__init__.py", line 1936, in create_context
ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "I:\AI\AI_202406\ComfyUI_windows_portable\python_embeded\Lib\site-packages\glcontext\__init__.py", line 51, in get_backend_by_name
raise ValueError("Cannot find supported backend: '{}'".format(name))

**Comment by tanglup** [comment]
> 只需再按一次[21d63f7](https://github.com/patriciogonzalezvivo/comfyui_glslnodes/commit/21d63f747d66f5217d60fc7c26a7c00ea66ad562)即可。你介意尝试一下吗？
> 
> 抱歉，来来回回。

(The error that occurred: AttributeError: module 'moderngl' has no attribute 'get_context'  )
 ---  also My moderngl version is 5.8.0，This version doesn't seem to work, which version do you recommend?
![4444](https://github.com/user-attachments/assets/f5a39a85-ca69-4946-912c-58426e88f19d)


![微信图片_20240716182050](https://github.com/user-attachments/assets/37121f64-c9a2-4cca-b203-d0539b10b650)

**Comment by ohnoitsaninja** [comment]
Fixed and working for me

**Comment by tanglup** [comment]
> That's great to hear! @tanglup I'm not sure why is not working. @ohnoitsaninja what version of `moderngl` is running on your machine? Are you using the portable version of comfyUI?

Yes, I'm using the official portable version

**Comment by patriciogonzalezvivo** [comment]
@ohnoitsaninja please upgrade the node and try again. It should be working now

**Comment by tanglup** [comment]
> 已修复并可供我使用

What version of moderngl can run smoothly?

**Comment by tanglup** [comment]
> 听到这个消息我很高兴！ @tanglup我不确定为什么不工作。@ohnoitsaninja您的机器上运行的是哪个版本`moderngl`？您使用的是便携版 comfyUI 吗？

After updating to moderngl==5.10.0, I was able to run

**Comment by tanglup** [comment]
> 听到这个消息我很高兴！ @tanglup我不确定为什么不工作。@ohnoitsaninja您的机器上运行的是哪个版本`moderngl`？您使用的是便携版 comfyUI 吗？

After updating to moderngl==5.10.0, I was able to run

**Comment by baram892** [comment]
I'm so happy Thank you guys~ it's working~~~ Thank you~~~~~~~~~~~~~~~
