### ISSUE TITLE
glslEditor convert code to input

### ISSUE THREAD

**Issue by ohnoitsaninja** [patriciogonzalezvivo/comfyui_glslnodes#5]
![image](https://github.com/user-attachments/assets/d58cdad4-4b27-4020-ad1f-347312954ec6)

Not every time, but occasionally when using 'convert widget to input' the code remains and multiple code nodes stack at the inputs, for as many times as you click convert to input

**Comment by patriciogonzalezvivo** [comment]
Mmm... not really sure what's going on there.
I'm also interested on the use case. You would like to feed a string as code?
