### ISSUE TITLE
Offset on selection and mouse interaction on ACE code editor 

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [patriciogonzalezvivo/comfyui_glslnodes#9]
@melMass @sofakid Thank you both for your implementations of ACE editor inside ComfyUI. I use them as references to use it for my shaedr editor. But I'm experiencing this error where the selection is offset by X lines depending on the zoom level of ComfyUI's viewport. I was wondering if you run into this issue and how did you solve it.

Thank you

![image](https://github.com/user-attachments/assets/e0aed164-2880-4542-9af5-e2ba0ef36ca9)

**Comment by sofakid** [comment]
Yes, cheers, glad you enjoyed it.

there is an editor setting hasCssTransforms, set that to true

**Comment by patriciogonzalezvivo** [comment]
That made the trick! Thank you very much!

**Comment by melMass** [comment]
TIL nice ! In mtb I don't use them on the node directly, so I didn't know that
